version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms3072m -Xmx3072m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - "~/esdata:/usr/share/elasticsearch/data"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.1
    container_name: kibana
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200


  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.1
    container_name: logstash
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5044:5044
    volumes:
      - "~/ELKF/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"

  jenkins:
    image: docker.io/jenkins/jenkins
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:5000
    volumes:
      - "/var/jenkins_home/:/var/jenkins_home/"

