filebeat.inputs:
  - type: log
    enabled: true
    paths:
      # 读取 docker 容器的日志
      - '/var/lib/docker/containers/*/*.log'
    # json 解析
    json.keys_under_root: false
    json.add_error_key: true
    json.overwrite_keys: true
    json.message_key: log
    # 多行配置
    multiline.pattern: '^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.?\d{0,3}'
    multiline.negate: true
    multiline.match: after

processors:
  - drop_fields:
      fields: ["@timestamp", "log", "file", "input", "host", "@version"]

output.logstash:
  enabled: true
  hosts: ["114.67.99.146:5044"]

