filebeat.inputs:
  - type: log
    enabled: true
    paths:
      # 读取 docker 容器的日志
      - '/var/lib/docker/containers/*/*.log'
    # json 解析
    json.keys_under_root: true
    json.add_error_key: true
    json.overwrite_keys: true
    json.message_key: log

    multiline.pattern: '^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.?\d{0,3}'
    multiline.negate: true
    multiline.match: after
output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

