filebeat.inputs:
  - type: container
    enabled: true
    paths:
      # 读取 docker 容器的日志
      - '/var/lib/docker/containers/*/*.log'
    # json 解析
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: log
output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

