filebeat.inputs:
  - type: container
    enabled: true
    paths:
      # 读取 docker 容器的日志
      - '/var/lib/docker/containers/*/*.log'
    # json 解析
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: log
    # 多行日志配置
    multiline.pattern: '^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.?\d{0,3}'
    multiline.negate: true
    multiline.match: after
output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

# docker run --name filebeat --link logstash -d -v ~/ELKF/config/cfg2/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml -v /var/lib/docker/containers/:/var/lib/docker/containers/ docker.elastic.co/beats/filebeat:7.4.1