filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /home/logs/pk_user/pk_user_info.log
    multiline.pattern: "^%{TIMESTAMP_ISO8601}"
    multiline.negate: true
    multiline.match: after
output.logstash:
  enabled: true
  hosts: ["logstash:5044"]